import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { generateAffiliateLink } from "../lib/affiliate";
import { calculateBestValue } from "../lib/bestValue";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL || "file:./dev.db",
});
const prisma = new PrismaClient();

const products = [
  // ============== RAM (10 products) ==============
  {
    name: "Corsair Vengeance LPX 16GB DDR4-3200",
    category: "ram",
    price: 44.99,
    rating: 4.7,
    reviewCount: 85234,
    imageUrl: "https://picsum.photos/seed/ram1/400/400",
    productUrl: "https://www.amazon.com/dp/B0143UM4TC",
    specs: JSON.stringify({ capacity: "16GB (2x8GB)", speed: "3200MHz", type: "DDR4", latency: "CL16", voltage: "1.35V", formFactor: "DIMM" }),
    featured: true,
  },
  {
    name: "G.Skill Trident Z5 RGB 32GB DDR5-6000",
    category: "ram",
    price: 109.99,
    rating: 4.8,
    reviewCount: 12450,
    imageUrl: "https://picsum.photos/seed/ram2/400/400",
    productUrl: "https://www.amazon.com/dp/B09QSJ5V8F",
    specs: JSON.stringify({ capacity: "32GB (2x16GB)", speed: "6000MHz", type: "DDR5", latency: "CL30", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "Kingston Fury Beast 16GB DDR5-5200",
    category: "ram",
    price: 54.99,
    rating: 4.6,
    reviewCount: 8932,
    imageUrl: "https://picsum.photos/seed/ram3/400/400",
    productUrl: "https://www.amazon.com/dp/B09WXDZL9C",
    specs: JSON.stringify({ capacity: "16GB (2x8GB)", speed: "5200MHz", type: "DDR5", latency: "CL40", voltage: "1.25V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "Corsair Dominator Platinum RGB 32GB DDR5-6200",
    category: "ram",
    price: 164.99,
    rating: 4.9,
    reviewCount: 4521,
    imageUrl: "https://picsum.photos/seed/ram4/400/400",
    productUrl: "https://www.amazon.com/dp/B0BF56MRYQ",
    specs: JSON.stringify({ capacity: "32GB (2x16GB)", speed: "6200MHz", type: "DDR5", latency: "CL30", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "Crucial Ballistix 16GB DDR4-3600",
    category: "ram",
    price: 59.99,
    rating: 4.7,
    reviewCount: 32145,
    imageUrl: "https://picsum.photos/seed/ram5/400/400",
    productUrl: "https://www.amazon.com/dp/B083TRRT16",
    specs: JSON.stringify({ capacity: "16GB (2x8GB)", speed: "3600MHz", type: "DDR4", latency: "CL16", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "TeamGroup T-Force Vulcan Z 16GB DDR4-3200",
    category: "ram",
    price: 34.99,
    rating: 4.5,
    reviewCount: 18234,
    imageUrl: "https://picsum.photos/seed/ram6/400/400",
    productUrl: "https://www.amazon.com/dp/B07T637L7T",
    specs: JSON.stringify({ capacity: "16GB (2x8GB)", speed: "3200MHz", type: "DDR4", latency: "CL16", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "G.Skill Ripjaws V 32GB DDR4-3600",
    category: "ram",
    price: 74.99,
    rating: 4.8,
    reviewCount: 45600,
    imageUrl: "https://picsum.photos/seed/ram7/400/400",
    productUrl: "https://www.amazon.com/dp/B07Z45XB3G",
    specs: JSON.stringify({ capacity: "32GB (2x16GB)", speed: "3600MHz", type: "DDR4", latency: "CL18", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "Corsair Vengeance 32GB DDR5-5600",
    category: "ram",
    price: 84.99,
    rating: 4.6,
    reviewCount: 9870,
    imageUrl: "https://picsum.photos/seed/ram8/400/400",
    productUrl: "https://www.amazon.com/dp/B0C3XQFRQG",
    specs: JSON.stringify({ capacity: "32GB (2x16GB)", speed: "5600MHz", type: "DDR5", latency: "CL36", voltage: "1.25V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "Kingston Fury Renegade 32GB DDR5-6400",
    category: "ram",
    price: 139.99,
    rating: 4.7,
    reviewCount: 3210,
    imageUrl: "https://picsum.photos/seed/ram9/400/400",
    productUrl: "https://www.amazon.com/dp/B0BQ9JWP3Y",
    specs: JSON.stringify({ capacity: "32GB (2x16GB)", speed: "6400MHz", type: "DDR5", latency: "CL32", voltage: "1.4V", formFactor: "DIMM" }),
    featured: false,
  },
  {
    name: "Patriot Viper Steel 16GB DDR4-4400",
    category: "ram",
    price: 79.99,
    rating: 4.4,
    reviewCount: 5430,
    imageUrl: "https://picsum.photos/seed/ram10/400/400",
    productUrl: "https://www.amazon.com/dp/B07KXNGMRL",
    specs: JSON.stringify({ capacity: "16GB (2x8GB)", speed: "4400MHz", type: "DDR4", latency: "CL19", voltage: "1.45V", formFactor: "DIMM" }),
    featured: false,
  },

  // ============== CPU (10 products) ==============
  {
    name: "AMD Ryzen 7 7800X3D",
    category: "cpu",
    price: 339.99,
    rating: 4.9,
    reviewCount: 28940,
    imageUrl: "https://picsum.photos/seed/cpu1/400/400",
    productUrl: "https://www.amazon.com/dp/B0BTZB7F88",
    specs: JSON.stringify({ cores: 8, threads: 16, baseClock: "4.2GHz", boostClock: "5.0GHz", cache: "104MB", tdp: "120W", socket: "AM5" }),
    featured: true,
  },
  {
    name: "Intel Core i5-14600K",
    category: "cpu",
    price: 249.99,
    rating: 4.7,
    reviewCount: 15230,
    imageUrl: "https://picsum.photos/seed/cpu2/400/400",
    productUrl: "https://www.amazon.com/dp/B0CGJ4MLC4",
    specs: JSON.stringify({ cores: 14, threads: 20, baseClock: "3.5GHz", boostClock: "5.3GHz", cache: "24MB", tdp: "125W", socket: "LGA1700" }),
    featured: false,
  },
  {
    name: "AMD Ryzen 5 7600X",
    category: "cpu",
    price: 199.99,
    rating: 4.8,
    reviewCount: 21500,
    imageUrl: "https://picsum.photos/seed/cpu3/400/400",
    productUrl: "https://www.amazon.com/dp/B0BBJM9Y9C",
    specs: JSON.stringify({ cores: 6, threads: 12, baseClock: "4.7GHz", boostClock: "5.3GHz", cache: "38MB", tdp: "105W", socket: "AM5" }),
    featured: false,
  },
  {
    name: "Intel Core i7-14700K",
    category: "cpu",
    price: 369.99,
    rating: 4.7,
    reviewCount: 9870,
    imageUrl: "https://picsum.photos/seed/cpu4/400/400",
    productUrl: "https://www.amazon.com/dp/B0CGJ7TM3Y",
    specs: JSON.stringify({ cores: 20, threads: 28, baseClock: "3.4GHz", boostClock: "5.6GHz", cache: "33MB", tdp: "125W", socket: "LGA1700" }),
    featured: false,
  },
  {
    name: "AMD Ryzen 9 7950X",
    category: "cpu",
    price: 549.99,
    rating: 4.8,
    reviewCount: 7840,
    imageUrl: "https://picsum.photos/seed/cpu5/400/400",
    productUrl: "https://www.amazon.com/dp/B0BBHHT8LY",
    specs: JSON.stringify({ cores: 16, threads: 32, baseClock: "4.5GHz", boostClock: "5.7GHz", cache: "80MB", tdp: "170W", socket: "AM5" }),
    featured: false,
  },
  {
    name: "Intel Core i9-14900K",
    category: "cpu",
    price: 549.99,
    rating: 4.6,
    reviewCount: 6540,
    imageUrl: "https://picsum.photos/seed/cpu6/400/400",
    productUrl: "https://www.amazon.com/dp/B0CGJ1WN3W",
    specs: JSON.stringify({ cores: 24, threads: 32, baseClock: "3.2GHz", boostClock: "6.0GHz", cache: "36MB", tdp: "125W", socket: "LGA1700" }),
    featured: false,
  },
  {
    name: "AMD Ryzen 5 5600X",
    category: "cpu",
    price: 139.99,
    rating: 4.8,
    reviewCount: 52300,
    imageUrl: "https://picsum.photos/seed/cpu7/400/400",
    productUrl: "https://www.amazon.com/dp/B08166SLDF",
    specs: JSON.stringify({ cores: 6, threads: 12, baseClock: "3.7GHz", boostClock: "4.6GHz", cache: "35MB", tdp: "65W", socket: "AM4" }),
    featured: false,
  },
  {
    name: "Intel Core i5-13400F",
    category: "cpu",
    price: 154.99,
    rating: 4.7,
    reviewCount: 18900,
    imageUrl: "https://picsum.photos/seed/cpu8/400/400",
    productUrl: "https://www.amazon.com/dp/B0BG64SLYZ",
    specs: JSON.stringify({ cores: 10, threads: 16, baseClock: "2.5GHz", boostClock: "4.6GHz", cache: "20MB", tdp: "65W", socket: "LGA1700" }),
    featured: false,
  },
  {
    name: "AMD Ryzen 7 5800X",
    category: "cpu",
    price: 194.99,
    rating: 4.7,
    reviewCount: 31200,
    imageUrl: "https://picsum.photos/seed/cpu9/400/400",
    productUrl: "https://www.amazon.com/dp/B0815XFSGK",
    specs: JSON.stringify({ cores: 8, threads: 16, baseClock: "3.8GHz", boostClock: "4.7GHz", cache: "36MB", tdp: "105W", socket: "AM4" }),
    featured: false,
  },
  {
    name: "Intel Core i3-13100F",
    category: "cpu",
    price: 94.99,
    rating: 4.5,
    reviewCount: 8760,
    imageUrl: "https://picsum.photos/seed/cpu10/400/400",
    productUrl: "https://www.amazon.com/dp/B0BG64G594",
    specs: JSON.stringify({ cores: 4, threads: 8, baseClock: "3.4GHz", boostClock: "4.5GHz", cache: "12MB", tdp: "58W", socket: "LGA1700" }),
    featured: false,
  },

  // ============== GPU (10 products) ==============
  {
    name: "NVIDIA GeForce RTX 4070 Super Founders Edition",
    category: "gpu",
    price: 599.99,
    rating: 4.8,
    reviewCount: 14520,
    imageUrl: "https://picsum.photos/seed/gpu1/400/400",
    productUrl: "https://www.amazon.com/dp/B0CS5JHWRJ",
    specs: JSON.stringify({ vram: "12GB GDDR6X", coreClock: "1980MHz", boostClock: "2475MHz", memoryBus: "192-bit", tdp: "220W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: true,
  },
  {
    name: "AMD Radeon RX 7800 XT",
    category: "gpu",
    price: 479.99,
    rating: 4.7,
    reviewCount: 8930,
    imageUrl: "https://picsum.photos/seed/gpu2/400/400",
    productUrl: "https://www.amazon.com/dp/B0CFHP4LPB",
    specs: JSON.stringify({ vram: "16GB GDDR6", coreClock: "1295MHz", boostClock: "2430MHz", memoryBus: "256-bit", tdp: "263W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
  },
  {
    name: "NVIDIA GeForce RTX 4060 Ti 8GB",
    category: "gpu",
    price: 399.99,
    rating: 4.6,
    reviewCount: 11240,
    imageUrl: "https://picsum.photos/seed/gpu3/400/400",
    productUrl: "https://www.amazon.com/dp/B0C7JCFYRN",
    specs: JSON.stringify({ vram: "8GB GDDR6", coreClock: "2310MHz", boostClock: "2535MHz", memoryBus: "128-bit", tdp: "160W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
  },
  {
    name: "NVIDIA GeForce RTX 4090 Founders Edition",
    category: "gpu",
    price: 1599.99,
    rating: 4.9,
    reviewCount: 6780,
    imageUrl: "https://picsum.photos/seed/gpu4/400/400",
    productUrl: "https://www.amazon.com/dp/B0BGP8FGNZ",
    specs: JSON.stringify({ vram: "24GB GDDR6X", coreClock: "2235MHz", boostClock: "2520MHz", memoryBus: "384-bit", tdp: "450W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
  },
  {
    name: "AMD Radeon RX 7600 8GB",
    category: "gpu",
    price: 249.99,
    rating: 4.5,
    reviewCount: 7650,
    imageUrl: "https://picsum.photos/seed/gpu5/400/400",
    productUrl: "https://www.amazon.com/dp/B0CM5JK3LG",
    specs: JSON.stringify({ vram: "8GB GDDR6", coreClock: "1720MHz", boostClock: "2655MHz", memoryBus: "128-bit", tdp: "165W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
  },
  {
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    category: "gpu",
    price: 799.99,
    rating: 4.8,
    reviewCount: 5430,
    imageUrl: "https://picsum.photos/seed/gpu6/400/400",
    productUrl: "https://www.amazon.com/dp/B0CS5K6R88",
    specs: JSON.stringify({ vram: "16GB GDDR6X", coreClock: "2340MHz", boostClock: "2610MHz", memoryBus: "256-bit", tdp: "285W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
  },
  {
    name: "NVIDIA GeForce RTX 4060 8GB",
    category: "gpu",
    price: 299.99,
    rating: 4.5,
    reviewCount: 15600,
    imageUrl: "https://picsum.photos/seed/gpu7/400/400",
    productUrl: "https://www.amazon.com/dp/B0C7JCFYSS",
    specs: JSON.stringify({ vram: "8GB GDDR6", coreClock: "1830MHz", boostClock: "2460MHz", memoryBus: "128-bit", tdp: "115W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
  },
  {
    name: "AMD Radeon RX 7900 XTX",
    category: "gpu",
    price: 899.99,
    rating: 4.7,
    reviewCount: 4890,
    imageUrl: "https://picsum.photos/seed/gpu8/400/400",
    productUrl: "https://www.amazon.com/dp/B0BZBGN2HR",
    specs: JSON.stringify({ vram: "24GB GDDR6", coreClock: "1855MHz", boostClock: "2500MHz", memoryBus: "384-bit", tdp: "355W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
  },
  {
    name: "Intel Arc A770 16GB",
    category: "gpu",
    price: 299.99,
    rating: 4.2,
    reviewCount: 6120,
    imageUrl: "https://picsum.photos/seed/gpu9/400/400",
    productUrl: "https://www.amazon.com/dp/B0BCXK2BYH",
    specs: JSON.stringify({ vram: "16GB GDDR6", coreClock: "2100MHz", boostClock: "2400MHz", memoryBus: "256-bit", tdp: "225W", ports: "HDMI 2.1, 2x DP 2.0" }),
    featured: false,
  },
  {
    name: "MSI GeForce RTX 4080 Super Gaming X Trio",
    category: "gpu",
    price: 1029.99,
    rating: 4.8,
    reviewCount: 3210,
    imageUrl: "https://picsum.photos/seed/gpu10/400/400",
    productUrl: "https://www.amazon.com/dp/B0CS5JKWWM",
    specs: JSON.stringify({ vram: "16GB GDDR6X", coreClock: "2295MHz", boostClock: "2610MHz", memoryBus: "256-bit", tdp: "320W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
  },

  // ============== Motherboard (10 products) ==============
  {
    name: "MSI MAG B650 Tomahawk WiFi",
    category: "motherboard",
    price: 199.99,
    rating: 4.7,
    reviewCount: 5430,
    imageUrl: "https://picsum.photos/seed/mb1/400/400",
    productUrl: "https://www.amazon.com/dp/B0BHCKJRTM",
    specs: JSON.stringify({ socket: "AM5", chipset: "B650", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 2, wifi: "WiFi 6E" }),
    featured: true,
  },
  {
    name: "ASUS ROG Strix B760-A Gaming WiFi D4",
    category: "motherboard",
    price: 179.99,
    rating: 4.6,
    reviewCount: 3280,
    imageUrl: "https://picsum.photos/seed/mb2/400/400",
    productUrl: "https://www.amazon.com/dp/B0BG6JNXJY",
    specs: JSON.stringify({ socket: "LGA1700", chipset: "B760", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 2, wifi: "WiFi 6" }),
    featured: false,
  },
  {
    name: "Gigabyte B550 AORUS Elite V2",
    category: "motherboard",
    price: 119.99,
    rating: 4.5,
    reviewCount: 12340,
    imageUrl: "https://picsum.photos/seed/mb3/400/400",
    productUrl: "https://www.amazon.com/dp/B08KWMXGPZ",
    specs: JSON.stringify({ socket: "AM4", chipset: "B550", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 2, wifi: "No" }),
    featured: false,
  },
  {
    name: "MSI PRO Z790-P WiFi DDR5",
    category: "motherboard",
    price: 219.99,
    rating: 4.7,
    reviewCount: 4560,
    imageUrl: "https://picsum.photos/seed/mb4/400/400",
    productUrl: "https://amzn.eu/d/0fL0heHC",
    specs: JSON.stringify({ socket: "LGA1700", chipset: "Z790", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 4, wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "ASUS ROG Crosshair X670E Hero",
    category: "motherboard",
    price: 499.99,
    rating: 4.8,
    reviewCount: 2340,
    imageUrl: "https://picsum.photos/seed/mb5/400/400",
    productUrl: "https://www.amazon.com/dp/B0BDTMT5K1",
    specs: JSON.stringify({ socket: "AM5", chipset: "X670E", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 5, wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "ASRock B660M Pro RS DDR4",
    category: "motherboard",
    price: 89.99,
    rating: 4.3,
    reviewCount: 6780,
    imageUrl: "https://picsum.photos/seed/mb6/400/400",
    productUrl: "https://www.amazon.com/dp/B09QYVMT2D",
    specs: JSON.stringify({ socket: "LGA1700", chipset: "B660", formFactor: "Micro-ATX", memorySlots: 2, maxMemory: "64GB", m2Slots: 1, wifi: "No" }),
    featured: false,
  },
  {
    name: "Gigabyte X670E AORUS Master",
    category: "motherboard",
    price: 389.99,
    rating: 4.7,
    reviewCount: 1890,
    imageUrl: "https://picsum.photos/seed/mb7/400/400",
    productUrl: "https://www.amazon.com/dp/B0BDTMSZW3",
    specs: JSON.stringify({ socket: "AM5", chipset: "X670E", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 4, wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "MSI MAG B550 Tomahawk",
    category: "motherboard",
    price: 139.99,
    rating: 4.7,
    reviewCount: 21000,
    imageUrl: "https://picsum.photos/seed/mb8/400/400",
    productUrl: "https://www.amazon.com/dp/B089CWDHFZ",
    specs: JSON.stringify({ socket: "AM4", chipset: "B550", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 2, wifi: "No" }),
    featured: false,
  },
  {
    name: "ASUS Prime B760M-A WiFi D4",
    category: "motherboard",
    price: 129.99,
    rating: 4.5,
    reviewCount: 7650,
    imageUrl: "https://picsum.photos/seed/mb9/400/400",
    productUrl: "https://www.amazon.com/dp/B0BG6MGL2G",
    specs: JSON.stringify({ socket: "LGA1700", chipset: "B760", formFactor: "Micro-ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 2, wifi: "WiFi 6" }),
    featured: false,
  },
  {
    name: "Gigabyte Z790 AORUS Elite AX DDR5",
    category: "motherboard",
    price: 249.99,
    rating: 4.6,
    reviewCount: 3120,
    imageUrl: "https://picsum.photos/seed/mb10/400/400",
    productUrl: "https://www.amazon.com/dp/B0BHC9SFKG",
    specs: JSON.stringify({ socket: "LGA1700", chipset: "Z790", formFactor: "ATX", memorySlots: 4, maxMemory: "128GB", m2Slots: 4, wifi: "WiFi 6E" }),
    featured: false,
  },

  // ============== Storage (10 products) ==============
  {
    name: "Samsung 990 Pro 2TB NVMe SSD",
    category: "storage",
    price: 169.99,
    rating: 4.8,
    reviewCount: 18740,
    imageUrl: "https://picsum.photos/seed/storage1/400/400",
    productUrl: "https://www.amazon.com/dp/B0BHJJ9Y77",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7450MB/s", writeSpeed: "6900MB/s", formFactor: "M.2 2280" }),
    featured: true,
  },
  {
    name: "WD Black SN850X 1TB",
    category: "storage",
    price: 79.99,
    rating: 4.8,
    reviewCount: 22100,
    imageUrl: "https://picsum.photos/seed/storage2/400/400",
    productUrl: "https://www.amazon.com/dp/B0B7CKVCCV",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7300MB/s", writeSpeed: "6300MB/s", formFactor: "M.2 2280" }),
    featured: false,
  },
  {
    name: "Crucial P3 Plus 1TB",
    category: "storage",
    price: 54.99,
    rating: 4.6,
    reviewCount: 14530,
    imageUrl: "https://picsum.photos/seed/storage3/400/400",
    productUrl: "https://www.amazon.com/dp/B0B25LZGGW",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "5000MB/s", writeSpeed: "4200MB/s", formFactor: "M.2 2280" }),
    featured: false,
  },
  {
    name: "Samsung 870 EVO 1TB SATA SSD",
    category: "storage",
    price: 69.99,
    rating: 4.8,
    reviewCount: 67800,
    imageUrl: "https://picsum.photos/seed/storage4/400/400",
    productUrl: "https://www.amazon.com/dp/B08QBJ2YMG",
    specs: JSON.stringify({ capacity: "1TB", type: "SATA SSD", interface: "SATA III", readSpeed: "560MB/s", writeSpeed: "530MB/s", formFactor: "2.5 inch" }),
    featured: false,
  },
  {
    name: "Seagate Barracuda 2TB HDD",
    category: "storage",
    price: 49.99,
    rating: 4.6,
    reviewCount: 89200,
    imageUrl: "https://picsum.photos/seed/storage5/400/400",
    productUrl: "https://www.amazon.com/dp/B07H2RR55Q",
    specs: JSON.stringify({ capacity: "2TB", type: "HDD", interface: "SATA III", rpm: "7200RPM", cache: "256MB", formFactor: "3.5 inch" }),
    featured: false,
  },
  {
    name: "SK Hynix Platinum P41 2TB",
    category: "storage",
    price: 149.99,
    rating: 4.8,
    reviewCount: 6540,
    imageUrl: "https://picsum.photos/seed/storage6/400/400",
    productUrl: "https://www.amazon.com/dp/B0B6DT57HV",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7000MB/s", writeSpeed: "6500MB/s", formFactor: "M.2 2280" }),
    featured: false,
  },
  {
    name: "Kingston NV2 500GB",
    category: "storage",
    price: 29.99,
    rating: 4.5,
    reviewCount: 11230,
    imageUrl: "https://picsum.photos/seed/storage7/400/400",
    productUrl: "https://www.amazon.com/dp/B0BBWH81F2",
    specs: JSON.stringify({ capacity: "500GB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "3500MB/s", writeSpeed: "2100MB/s", formFactor: "M.2 2280" }),
    featured: false,
  },
  {
    name: "Corsair MP600 PRO LPX 2TB",
    category: "storage",
    price: 189.99,
    rating: 4.7,
    reviewCount: 4320,
    imageUrl: "https://picsum.photos/seed/storage8/400/400",
    productUrl: "https://www.amazon.com/dp/B0B27RCWPF",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7100MB/s", writeSpeed: "6800MB/s", formFactor: "M.2 2280" }),
    featured: false,
  },
  {
    name: "WD Blue SA510 1TB SATA SSD",
    category: "storage",
    price: 59.99,
    rating: 4.5,
    reviewCount: 9870,
    imageUrl: "https://picsum.photos/seed/storage9/400/400",
    productUrl: "https://www.amazon.com/dp/B09HKGGPLR",
    specs: JSON.stringify({ capacity: "1TB", type: "SATA SSD", interface: "SATA III", readSpeed: "560MB/s", writeSpeed: "520MB/s", formFactor: "2.5 inch" }),
    featured: false,
  },
  {
    name: "Sabrent Rocket 4 Plus-G 4TB",
    category: "storage",
    price: 349.99,
    rating: 4.7,
    reviewCount: 2140,
    imageUrl: "https://picsum.photos/seed/storage10/400/400",
    productUrl: "https://www.amazon.com/dp/B0BYZ1Y45R",
    specs: JSON.stringify({ capacity: "4TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7100MB/s", writeSpeed: "6600MB/s", formFactor: "M.2 2280" }),
    featured: false,
  },

  // ============== PC Case (10 products) ==============
  {
    name: "NZXT H5 Flow",
    category: "case",
    price: 94.99,
    rating: 4.7,
    reviewCount: 8970,
    imageUrl: "https://picsum.photos/seed/case1/400/400",
    productUrl: "https://www.amazon.com/dp/B0B6CG9BLH",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "18.1 x 8.6 x 17.1 in", driveSlots: "2x 2.5\", 1x 3.5\"", fanSupport: "6x 120mm", maxGpuLength: "365mm", frontIO: "USB-C, 2x USB-A" }),
    featured: true,
  },
  {
    name: "Corsair 4000D Airflow",
    category: "case",
    price: 104.99,
    rating: 4.7,
    reviewCount: 32100,
    imageUrl: "https://picsum.photos/seed/case2/400/400",
    productUrl: "https://www.amazon.com/dp/B08C76W2WM",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "18.7 x 9.1 x 17.8 in", driveSlots: "2x 2.5\", 2x 3.5\"", fanSupport: "6x 120mm", maxGpuLength: "360mm", frontIO: "USB-C, USB-A" }),
    featured: false,
  },
  {
    name: "Fractal Design North",
    category: "case",
    price: 139.99,
    rating: 4.8,
    reviewCount: 5430,
    imageUrl: "https://picsum.photos/seed/case3/400/400",
    productUrl: "https://www.amazon.com/dp/B0BYCQYHLW",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "18.3 x 8.5 x 17.6 in", driveSlots: "2x 2.5\", 2x 3.5\"", fanSupport: "6x 120mm / 3x 140mm", maxGpuLength: "355mm", frontIO: "USB-C, 2x USB-A" }),
    featured: false,
  },
  {
    name: "Lian Li Lancool II Mesh",
    category: "case",
    price: 109.99,
    rating: 4.8,
    reviewCount: 14500,
    imageUrl: "https://picsum.photos/seed/case4/400/400",
    productUrl: "https://www.amazon.com/dp/B08DX68X8S",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "19.0 x 9.0 x 18.5 in", driveSlots: "3x 2.5\", 2x 3.5\"", fanSupport: "7x 120mm", maxGpuLength: "384mm", frontIO: "USB-C, 2x USB-A" }),
    featured: false,
  },
  {
    name: "Phanteks Eclipse G360A",
    category: "case",
    price: 89.99,
    rating: 4.6,
    reviewCount: 7890,
    imageUrl: "https://picsum.photos/seed/case5/400/400",
    productUrl: "https://www.amazon.com/dp/B09GFR7TL5",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "18.5 x 8.3 x 17.1 in", driveSlots: "2x 2.5\", 2x 3.5\"", fanSupport: "6x 120mm", maxGpuLength: "380mm", frontIO: "USB-C, USB-A" }),
    featured: false,
  },
  {
    name: "be quiet! Pure Base 500DX",
    category: "case",
    price: 109.99,
    rating: 4.7,
    reviewCount: 9340,
    imageUrl: "https://picsum.photos/seed/case6/400/400",
    productUrl: "https://www.amazon.com/dp/B087TNVS2Z",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "18.9 x 9.1 x 17.5 in", driveSlots: "5x 2.5\", 2x 3.5\"", fanSupport: "5x 120mm / 140mm", maxGpuLength: "369mm", frontIO: "USB-C, 2x USB-A" }),
    featured: false,
  },
  {
    name: "Cooler Master MasterBox Q300L",
    category: "case",
    price: 49.99,
    rating: 4.4,
    reviewCount: 18700,
    imageUrl: "https://picsum.photos/seed/case7/400/400",
    productUrl: "https://www.amazon.com/dp/B0785GRMPG",
    specs: JSON.stringify({ formFactor: "Micro-ATX", dimensions: "15.6 x 9.1 x 14.8 in", driveSlots: "1x 2.5\", 1x 3.5\"", fanSupport: "4x 120mm", maxGpuLength: "360mm", frontIO: "2x USB-A" }),
    featured: false,
  },
  {
    name: "Lian Li O11 Dynamic EVO",
    category: "case",
    price: 169.99,
    rating: 4.8,
    reviewCount: 6780,
    imageUrl: "https://picsum.photos/seed/case8/400/400",
    productUrl: "https://www.amazon.com/dp/B09TMHKBRP",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "20.2 x 11.2 x 18.6 in", driveSlots: "4x 2.5\", 2x 3.5\"", fanSupport: "9x 120mm", maxGpuLength: "422mm", frontIO: "USB-C, 2x USB-A" }),
    featured: false,
  },
  {
    name: "Thermaltake S100 TG",
    category: "case",
    price: 64.99,
    rating: 4.3,
    reviewCount: 4560,
    imageUrl: "https://picsum.photos/seed/case9/400/400",
    productUrl: "https://www.amazon.com/dp/B08GQD7Y5J",
    specs: JSON.stringify({ formFactor: "Micro-ATX", dimensions: "16.7 x 8.0 x 15.0 in", driveSlots: "2x 2.5\", 2x 3.5\"", fanSupport: "4x 120mm", maxGpuLength: "330mm", frontIO: "USB-A x2" }),
    featured: false,
  },
  {
    name: "Corsair 5000D Airflow",
    category: "case",
    price: 164.99,
    rating: 4.7,
    reviewCount: 8900,
    imageUrl: "https://picsum.photos/seed/case10/400/400",
    productUrl: "https://www.amazon.com/dp/B08C7BGV3J",
    specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: "20.5 x 9.1 x 20.5 in", driveSlots: "4x 2.5\", 2x 3.5\"", fanSupport: "10x 120mm", maxGpuLength: "420mm", frontIO: "USB-C, 2x USB-A, Audio" }),
    featured: false,
  },

  // ============== Cooling (10 products) ==============
  {
    name: "Noctua NH-D15",
    category: "cooling",
    price: 109.99,
    rating: 4.9,
    reviewCount: 24500,
    imageUrl: "https://picsum.photos/seed/cool1/400/400",
    productUrl: "https://www.amazon.com/dp/B00L7UZMAK",
    specs: JSON.stringify({ type: "Air Cooler", fanSize: "2x 140mm", height: "165mm", tdpRating: "250W+", noise: "24.6 dBA", socket: "Intel & AMD" }),
    featured: true,
  },
  {
    name: "Corsair iCUE H150i Elite Capellix",
    category: "cooling",
    price: 169.99,
    rating: 4.7,
    reviewCount: 11230,
    imageUrl: "https://picsum.photos/seed/cool2/400/400",
    productUrl: "https://www.amazon.com/dp/B08G1LPKGC",
    specs: JSON.stringify({ type: "AIO Liquid 360mm", fanSize: "3x 120mm", radiator: "360mm", tdpRating: "300W+", noise: "10-36 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "be quiet! Dark Rock Pro 4",
    category: "cooling",
    price: 89.99,
    rating: 4.8,
    reviewCount: 13400,
    imageUrl: "https://picsum.photos/seed/cool3/400/400",
    productUrl: "https://www.amazon.com/dp/B07BY6F1TI",
    specs: JSON.stringify({ type: "Air Cooler", fanSize: "1x 120mm + 1x 135mm", height: "163mm", tdpRating: "250W", noise: "24.3 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "ARCTIC Liquid Freezer II 280",
    category: "cooling",
    price: 99.99,
    rating: 4.8,
    reviewCount: 8760,
    imageUrl: "https://picsum.photos/seed/cool4/400/400",
    productUrl: "https://www.amazon.com/dp/B07WP6M7P7",
    specs: JSON.stringify({ type: "AIO Liquid 280mm", fanSize: "2x 140mm", radiator: "280mm", tdpRating: "300W+", noise: "22.5 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "Thermalright Peerless Assassin 120 SE",
    category: "cooling",
    price: 35.99,
    rating: 4.7,
    reviewCount: 15600,
    imageUrl: "https://picsum.photos/seed/cool5/400/400",
    productUrl: "https://www.amazon.com/dp/B09LGY38L4",
    specs: JSON.stringify({ type: "Air Cooler", fanSize: "2x 120mm", height: "155mm", tdpRating: "230W", noise: "25.6 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "NZXT Kraken X63",
    category: "cooling",
    price: 119.99,
    rating: 4.6,
    reviewCount: 7650,
    imageUrl: "https://picsum.photos/seed/cool6/400/400",
    productUrl: "https://www.amazon.com/dp/B082DYR131",
    specs: JSON.stringify({ type: "AIO Liquid 280mm", fanSize: "2x 140mm", radiator: "280mm", tdpRating: "280W", noise: "21-38 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "Cooler Master Hyper 212 EVO V2",
    category: "cooling",
    price: 34.99,
    rating: 4.5,
    reviewCount: 42100,
    imageUrl: "https://picsum.photos/seed/cool7/400/400",
    productUrl: "https://www.amazon.com/dp/B08LR3SBT8",
    specs: JSON.stringify({ type: "Air Cooler", fanSize: "1x 120mm", height: "159mm", tdpRating: "150W", noise: "27 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "DeepCool AK620",
    category: "cooling",
    price: 64.99,
    rating: 4.8,
    reviewCount: 9340,
    imageUrl: "https://picsum.photos/seed/cool8/400/400",
    productUrl: "https://www.amazon.com/dp/B09DJFKHCJ",
    specs: JSON.stringify({ type: "Air Cooler", fanSize: "2x 120mm", height: "160mm", tdpRating: "260W", noise: "28 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "Lian Li Galahad II Trinity 360",
    category: "cooling",
    price: 149.99,
    rating: 4.7,
    reviewCount: 3210,
    imageUrl: "https://picsum.photos/seed/cool9/400/400",
    productUrl: "https://www.amazon.com/dp/B0CN18WQXY",
    specs: JSON.stringify({ type: "AIO Liquid 360mm", fanSize: "3x 120mm", radiator: "360mm", tdpRating: "300W+", noise: "29 dBA", socket: "Intel & AMD" }),
    featured: false,
  },
  {
    name: "ID-COOLING SE-214-XT",
    category: "cooling",
    price: 19.99,
    rating: 4.5,
    reviewCount: 16780,
    imageUrl: "https://picsum.photos/seed/cool10/400/400",
    productUrl: "https://www.amazon.com/dp/B09BQNQKPS",
    specs: JSON.stringify({ type: "Air Cooler", fanSize: "1x 120mm", height: "150mm", tdpRating: "180W", noise: "26.2 dBA", socket: "Intel & AMD" }),
    featured: false,
  },

  // ============== PSU (10 products) ==============
  {
    name: "Corsair RM850x (2023)",
    category: "psu",
    price: 139.99,
    rating: 4.8,
    reviewCount: 15600,
    imageUrl: "https://picsum.photos/seed/psu1/400/400",
    productUrl: "https://www.amazon.com/dp/B0BYM5YPC3",
    specs: JSON.stringify({ wattage: "850W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP", warranty: "10 years" }),
    featured: true,
  },
  {
    name: "EVGA SuperNOVA 750 G7",
    category: "psu",
    price: 109.99,
    rating: 4.7,
    reviewCount: 8930,
    imageUrl: "https://picsum.photos/seed/psu2/400/400",
    productUrl: "https://www.amazon.com/dp/B09J2JBQJZ",
    specs: JSON.stringify({ wattage: "750W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "130mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }),
    featured: false,
  },
  {
    name: "Seasonic Focus GX-650",
    category: "psu",
    price: 89.99,
    rating: 4.7,
    reviewCount: 12300,
    imageUrl: "https://picsum.photos/seed/psu3/400/400",
    productUrl: "https://www.amazon.com/dp/B077J9QTDR",
    specs: JSON.stringify({ wattage: "650W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "120mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "10 years" }),
    featured: false,
  },
  {
    name: "be quiet! Straight Power 12 1000W",
    category: "psu",
    price: 189.99,
    rating: 4.8,
    reviewCount: 3450,
    imageUrl: "https://picsum.photos/seed/psu4/400/400",
    productUrl: "https://www.amazon.com/dp/B0BMDX5C9N",
    specs: JSON.stringify({ wattage: "1000W", efficiency: "80+ Platinum", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "10 years" }),
    featured: false,
  },
  {
    name: "Thermaltake Toughpower GF3 850W",
    category: "psu",
    price: 119.99,
    rating: 4.6,
    reviewCount: 5670,
    imageUrl: "https://picsum.photos/seed/psu5/400/400",
    productUrl: "https://www.amazon.com/dp/B0BGPCHTQN",
    specs: JSON.stringify({ wattage: "850W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "120mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }),
    featured: false,
  },
  {
    name: "Corsair CX550F RGB",
    category: "psu",
    price: 69.99,
    rating: 4.4,
    reviewCount: 9870,
    imageUrl: "https://picsum.photos/seed/psu6/400/400",
    productUrl: "https://www.amazon.com/dp/B08FVKRC96",
    specs: JSON.stringify({ wattage: "550W", efficiency: "80+ Bronze", modular: "Fully Modular", fanSize: "120mm RGB", protections: "OVP, UVP, SCP, OTP", warranty: "5 years" }),
    featured: false,
  },
  {
    name: "NZXT C1200 Gold",
    category: "psu",
    price: 199.99,
    rating: 4.7,
    reviewCount: 2340,
    imageUrl: "https://picsum.photos/seed/psu7/400/400",
    productUrl: "https://www.amazon.com/dp/B0CK3MB12V",
    specs: JSON.stringify({ wattage: "1200W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "140mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }),
    featured: false,
  },
  {
    name: "MSI MAG A650BN",
    category: "psu",
    price: 54.99,
    rating: 4.3,
    reviewCount: 6540,
    imageUrl: "https://picsum.photos/seed/psu8/400/400",
    productUrl: "https://www.amazon.com/dp/B0BGPR87TG",
    specs: JSON.stringify({ wattage: "650W", efficiency: "80+ Bronze", modular: "Non-Modular", fanSize: "120mm", protections: "OVP, UVP, SCP, OTP", warranty: "5 years" }),
    featured: false,
  },
  {
    name: "Corsair HX1500i",
    category: "psu",
    price: 349.99,
    rating: 4.9,
    reviewCount: 1890,
    imageUrl: "https://picsum.photos/seed/psu9/400/400",
    productUrl: "https://www.amazon.com/dp/B0BTFX94N3",
    specs: JSON.stringify({ wattage: "1500W", efficiency: "80+ Platinum", modular: "Fully Modular", fanSize: "140mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "10 years" }),
    featured: false,
  },
  {
    name: "Cooler Master V750 SFX Gold",
    category: "psu",
    price: 124.99,
    rating: 4.6,
    reviewCount: 4560,
    imageUrl: "https://picsum.photos/seed/psu10/400/400",
    productUrl: "https://www.amazon.com/dp/B09NS5YB3F",
    specs: JSON.stringify({ wattage: "750W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "92mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }),
    featured: false,
  },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);

  // Group by category to calculate bestValue
  const byCategory: Record<string, typeof products> = {};
  for (const p of products) {
    if (!byCategory[p.category]) byCategory[p.category] = [];
    byCategory[p.category].push(p);
  }

  let count = 0;
  for (const [category, group] of Object.entries(byCategory)) {
    console.log(`  Category: ${category} (${group.length} products)`);
    for (const p of group) {
      const bestValue = calculateBestValue(p, group);
      const affiliateUrl = generateAffiliateLink(p.productUrl);

      await prisma.product.create({
        data: {
          name: p.name,
          category: p.category,
          price: p.price,
          rating: p.rating,
          reviewCount: p.reviewCount,
          imageUrl: p.imageUrl,
          productUrl: p.productUrl,
          affiliateUrl,
          specs: p.specs,
          bestValue,
          featured: p.featured,
          inStock: true,
        },
      });
      count++;
    }
  }

  console.log(`\nSeed complete. ${count} products created.`);
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
