import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { generateAffiliateLink } from "../lib/affiliate";
import { calculateBestValue } from "../lib/bestValue";

const prisma = new PrismaClient();

// ─────────────────────────────────────────────────────────────────────────────
// Product seed data — 15 products per category (8 categories = 120 total)
// All prices reflect realistic 2026 market pricing.
// Image URLs use Amazon product image CDN format.
// ─────────────────────────────────────────────────────────────────────────────

interface SeedProduct {
  name: string;
  category: string;
  price: number;
  rating: number;
  reviewCount: number;
  imageUrl: string;
  productUrl: string;
  specs: string;
  featured: boolean;
  description?: string;
}

const products: SeedProduct[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // CPU — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "AMD Ryzen 7 7800X3D",
    category: "cpu",
    price: 329.99,
    rating: 4.9,
    reviewCount: 32400,
    imageUrl: "https://m.media-amazon.com/images/I/51-n-GQdYzL._AC_SL1200_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BTZB7F88",
    specs: JSON.stringify({ cores: "8", threads: "16", baseClock: "4.2 GHz", boostClock: "5.0 GHz", cache: "104MB (3D V-Cache)", tdp: "120W", socket: "AM5" }),
    featured: true,
    description: "The #1 gaming CPU with revolutionary 3D V-Cache technology.",
  },
  {
    name: "Intel Core i5-14600K",
    category: "cpu",
    price: 239.99,
    rating: 4.7,
    reviewCount: 18200,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CGJ4MLC4",
    specs: JSON.stringify({ cores: "14 (6P+8E)", threads: "20", baseClock: "3.5 GHz", boostClock: "5.3 GHz", cache: "24MB", tdp: "125W", socket: "LGA 1700" }),
    featured: false,
    description: "Excellent mid-range CPU balancing gaming and productivity.",
  },
  {
    name: "AMD Ryzen 9 7950X",
    category: "cpu",
    price: 479.99,
    rating: 4.8,
    reviewCount: 9800,
    imageUrl: "https://m.media-amazon.com/images/I/51wrOkv3HSL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BBHHT8LY",
    specs: JSON.stringify({ cores: "16", threads: "32", baseClock: "4.5 GHz", boostClock: "5.7 GHz", cache: "80MB", tdp: "170W", socket: "AM5" }),
    featured: false,
    description: "Ultimate workstation CPU with 16 cores for heavy multitasking.",
  },
  {
    name: "Intel Core i9-14900K",
    category: "cpu",
    price: 519.99,
    rating: 4.6,
    reviewCount: 8900,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CGJ1WN3W",
    specs: JSON.stringify({ cores: "24 (8P+16E)", threads: "32", baseClock: "3.2 GHz", boostClock: "6.0 GHz", cache: "36MB", tdp: "125W", socket: "LGA 1700" }),
    featured: false,
    description: "Intel's flagship with 24 cores and 6.0 GHz boost clock.",
  },
  {
    name: "AMD Ryzen 5 7600X",
    category: "cpu",
    price: 189.99,
    rating: 4.8,
    reviewCount: 24500,
    imageUrl: "https://m.media-amazon.com/images/I/51wrOkv3HSL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BBJM9Y9C",
    specs: JSON.stringify({ cores: "6", threads: "12", baseClock: "4.7 GHz", boostClock: "5.3 GHz", cache: "38MB", tdp: "105W", socket: "AM5" }),
    featured: false,
    description: "Best budget AM5 gaming CPU with excellent single-threaded performance.",
  },
  {
    name: "Intel Core i7-14700K",
    category: "cpu",
    price: 349.99,
    rating: 4.7,
    reviewCount: 12100,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CGJ7TM3Y",
    specs: JSON.stringify({ cores: "20 (8P+12E)", threads: "28", baseClock: "3.4 GHz", boostClock: "5.6 GHz", cache: "33MB", tdp: "125W", socket: "LGA 1700" }),
    featured: false,
    description: "Powerhouse for gaming and content creation with 20 cores.",
  },
  {
    name: "AMD Ryzen 5 5600X",
    category: "cpu",
    price: 129.99,
    rating: 4.8,
    reviewCount: 58000,
    imageUrl: "https://m.media-amazon.com/images/I/61IIbwz-+ML._AC_SL1384_.jpg",
    productUrl: "https://www.amazon.com/dp/B08166SLDF",
    specs: JSON.stringify({ cores: "6", threads: "12", baseClock: "3.7 GHz", boostClock: "4.6 GHz", cache: "35MB", tdp: "65W", socket: "AM4" }),
    featured: false,
    description: "Legendary value AM4 CPU — still an excellent choice for 1080p gaming.",
  },
  {
    name: "Intel Core i5-13400F",
    category: "cpu",
    price: 144.99,
    rating: 4.7,
    reviewCount: 21000,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BG64SLYZ",
    specs: JSON.stringify({ cores: "10 (6P+4E)", threads: "16", baseClock: "2.5 GHz", boostClock: "4.6 GHz", cache: "20MB", tdp: "65W", socket: "LGA 1700" }),
    featured: false,
    description: "Budget Intel option with 10 cores and no integrated graphics.",
  },
  {
    name: "AMD Ryzen 7 5800X",
    category: "cpu",
    price: 179.99,
    rating: 4.7,
    reviewCount: 35000,
    imageUrl: "https://m.media-amazon.com/images/I/61IIbwz-+ML._AC_SL1384_.jpg",
    productUrl: "https://www.amazon.com/dp/B0815XFSGK",
    specs: JSON.stringify({ cores: "8", threads: "16", baseClock: "3.8 GHz", boostClock: "4.7 GHz", cache: "36MB", tdp: "105W", socket: "AM4" }),
    featured: false,
    description: "Strong 8-core AM4 CPU for gaming and streaming.",
  },
  {
    name: "Intel Core i3-13100F",
    category: "cpu",
    price: 89.99,
    rating: 4.5,
    reviewCount: 10200,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BG64G594",
    specs: JSON.stringify({ cores: "4", threads: "8", baseClock: "3.4 GHz", boostClock: "4.5 GHz", cache: "12MB", tdp: "58W", socket: "LGA 1700" }),
    featured: false,
    description: "Entry-level quad-core for budget builds.",
  },
  {
    name: "AMD Ryzen 9 7900X",
    category: "cpu",
    price: 379.99,
    rating: 4.7,
    reviewCount: 7600,
    imageUrl: "https://m.media-amazon.com/images/I/51wrOkv3HSL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BBJ59WJ4",
    specs: JSON.stringify({ cores: "12", threads: "24", baseClock: "4.7 GHz", boostClock: "5.6 GHz", cache: "76MB", tdp: "170W", socket: "AM5" }),
    featured: false,
    description: "12-core powerhouse for gaming and creative workloads.",
  },
  {
    name: "Intel Core i5-12400F",
    category: "cpu",
    price: 109.99,
    rating: 4.7,
    reviewCount: 42000,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B09NMPD8V2",
    specs: JSON.stringify({ cores: "6", threads: "12", baseClock: "2.5 GHz", boostClock: "4.4 GHz", cache: "18MB", tdp: "65W", socket: "LGA 1700" }),
    featured: false,
    description: "Previous-gen value king — great for budget gaming rigs.",
  },
  {
    name: "AMD Ryzen 7 7700X",
    category: "cpu",
    price: 279.99,
    rating: 4.7,
    reviewCount: 11800,
    imageUrl: "https://m.media-amazon.com/images/I/51wrOkv3HSL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BBHHT8LY",
    specs: JSON.stringify({ cores: "8", threads: "16", baseClock: "4.5 GHz", boostClock: "5.4 GHz", cache: "40MB", tdp: "105W", socket: "AM5" }),
    featured: false,
    description: "Solid 8-core AM5 CPU for gaming and multitasking.",
  },
  {
    name: "Intel Core i9-13900K",
    category: "cpu",
    price: 449.99,
    rating: 4.6,
    reviewCount: 14500,
    imageUrl: "https://m.media-amazon.com/images/I/51hSs-bkZAL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BCF54SR1",
    specs: JSON.stringify({ cores: "24 (8P+16E)", threads: "32", baseClock: "3.0 GHz", boostClock: "5.8 GHz", cache: "36MB", tdp: "125W", socket: "LGA 1700" }),
    featured: false,
    description: "Previous-gen flagship with excellent multi-threaded performance.",
  },
  {
    name: "AMD Ryzen 5 5600",
    category: "cpu",
    price: 109.99,
    rating: 4.8,
    reviewCount: 16000,
    imageUrl: "https://m.media-amazon.com/images/I/61IIbwz-+ML._AC_SL1384_.jpg",
    productUrl: "https://www.amazon.com/dp/B09VCJ2SHG",
    specs: JSON.stringify({ cores: "6", threads: "12", baseClock: "3.5 GHz", boostClock: "4.4 GHz", cache: "35MB", tdp: "65W", socket: "AM4" }),
    featured: false,
    description: "Non-X variant — slightly lower clocks, includes a cooler.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GPU — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "NVIDIA GeForce RTX 4090 Founders Edition",
    category: "gpu",
    price: 1599.99,
    rating: 4.9,
    reviewCount: 8200,
    imageUrl: "https://m.media-amazon.com/images/I/61NVfoVx0QL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BGP8FGNZ",
    specs: JSON.stringify({ vram: "24GB GDDR6X", coreClock: "2235 MHz", boostClock: "2520 MHz", memoryBus: "384-bit", tdp: "450W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: true,
    description: "The ultimate GPU for 4K gaming and AI workloads.",
  },
  {
    name: "NVIDIA GeForce RTX 4070 Super",
    category: "gpu",
    price: 579.99,
    rating: 4.8,
    reviewCount: 16500,
    imageUrl: "https://m.media-amazon.com/images/I/61bSp+hfIQL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CS5JHWRJ",
    specs: JSON.stringify({ vram: "12GB GDDR6X", coreClock: "1980 MHz", boostClock: "2475 MHz", memoryBus: "192-bit", tdp: "220W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: true,
    description: "Excellent 1440p performance with DLSS 3 frame generation.",
  },
  {
    name: "AMD Radeon RX 7800 XT",
    category: "gpu",
    price: 459.99,
    rating: 4.7,
    reviewCount: 10500,
    imageUrl: "https://m.media-amazon.com/images/I/51eHGCy8C-L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CFHP4LPB",
    specs: JSON.stringify({ vram: "16GB GDDR6", coreClock: "1295 MHz", boostClock: "2430 MHz", memoryBus: "256-bit", tdp: "263W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
    description: "Best-in-class 1440p gaming with 16GB VRAM for future-proofing.",
  },
  {
    name: "NVIDIA GeForce RTX 4060 Ti 8GB",
    category: "gpu",
    price: 379.99,
    rating: 4.6,
    reviewCount: 13200,
    imageUrl: "https://m.media-amazon.com/images/I/61YGKJ42mUL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0C7JCFYRN",
    specs: JSON.stringify({ vram: "8GB GDDR6", coreClock: "2310 MHz", boostClock: "2535 MHz", memoryBus: "128-bit", tdp: "160W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "Solid 1080p/1440p GPU with excellent power efficiency.",
  },
  {
    name: "NVIDIA GeForce RTX 4060",
    category: "gpu",
    price: 289.99,
    rating: 4.5,
    reviewCount: 18000,
    imageUrl: "https://m.media-amazon.com/images/I/61YGKJ42mUL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0C7JCFYSS",
    specs: JSON.stringify({ vram: "8GB GDDR6", coreClock: "1830 MHz", boostClock: "2460 MHz", memoryBus: "128-bit", tdp: "115W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "Budget-friendly 1080p GPU with DLSS 3 support.",
  },
  {
    name: "AMD Radeon RX 7600 8GB",
    category: "gpu",
    price: 239.99,
    rating: 4.5,
    reviewCount: 9200,
    imageUrl: "https://m.media-amazon.com/images/I/51eHGCy8C-L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CM5JK3LG",
    specs: JSON.stringify({ vram: "8GB GDDR6", coreClock: "1720 MHz", boostClock: "2655 MHz", memoryBus: "128-bit", tdp: "165W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
    description: "AMD's budget 1080p gaming card with excellent value.",
  },
  {
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    category: "gpu",
    price: 769.99,
    rating: 4.8,
    reviewCount: 6400,
    imageUrl: "https://m.media-amazon.com/images/I/61bSp+hfIQL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CS5K6R88",
    specs: JSON.stringify({ vram: "16GB GDDR6X", coreClock: "2340 MHz", boostClock: "2610 MHz", memoryBus: "256-bit", tdp: "285W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "High-end 1440p/4K card with 16GB VRAM.",
  },
  {
    name: "AMD Radeon RX 7900 XTX",
    category: "gpu",
    price: 849.99,
    rating: 4.7,
    reviewCount: 5800,
    imageUrl: "https://m.media-amazon.com/images/I/51eHGCy8C-L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BZBGN2HR",
    specs: JSON.stringify({ vram: "24GB GDDR6", coreClock: "1855 MHz", boostClock: "2500 MHz", memoryBus: "384-bit", tdp: "355W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
    description: "AMD's flagship with 24GB VRAM for 4K gaming and content creation.",
  },
  {
    name: "MSI GeForce RTX 4080 Super Gaming X Trio",
    category: "gpu",
    price: 979.99,
    rating: 4.8,
    reviewCount: 4200,
    imageUrl: "https://m.media-amazon.com/images/I/61bSp+hfIQL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CS5JKWWM",
    specs: JSON.stringify({ vram: "16GB GDDR6X", coreClock: "2295 MHz", boostClock: "2610 MHz", memoryBus: "256-bit", tdp: "320W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "Premium RTX 4080 Super with exceptional cooling.",
  },
  {
    name: "Intel Arc A770 16GB",
    category: "gpu",
    price: 279.99,
    rating: 4.2,
    reviewCount: 7100,
    imageUrl: "https://m.media-amazon.com/images/I/61tkBBfh9mL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BCXK2BYH",
    specs: JSON.stringify({ vram: "16GB GDDR6", coreClock: "2100 MHz", boostClock: "2400 MHz", memoryBus: "256-bit", tdp: "225W", ports: "HDMI 2.1, 2x DP 2.0" }),
    featured: false,
    description: "Intel's best GPU — great value with AV1 encoding.",
  },
  {
    name: "NVIDIA GeForce RTX 4070",
    category: "gpu",
    price: 529.99,
    rating: 4.7,
    reviewCount: 11000,
    imageUrl: "https://m.media-amazon.com/images/I/61bSp+hfIQL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BVJFB3LY",
    specs: JSON.stringify({ vram: "12GB GDDR6X", coreClock: "1920 MHz", boostClock: "2475 MHz", memoryBus: "192-bit", tdp: "200W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "Non-Super variant — still excellent for 1440p gaming.",
  },
  {
    name: "AMD Radeon RX 7900 XT",
    category: "gpu",
    price: 699.99,
    rating: 4.6,
    reviewCount: 5200,
    imageUrl: "https://m.media-amazon.com/images/I/51eHGCy8C-L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BZBG2NKR",
    specs: JSON.stringify({ vram: "20GB GDDR6", coreClock: "1500 MHz", boostClock: "2400 MHz", memoryBus: "320-bit", tdp: "315W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
    description: "20GB VRAM for serious 4K gaming at a lower price than XTX.",
  },
  {
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    category: "gpu",
    price: 449.99,
    rating: 4.5,
    reviewCount: 4800,
    imageUrl: "https://m.media-amazon.com/images/I/61YGKJ42mUL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CG5KNLC5",
    specs: JSON.stringify({ vram: "16GB GDDR6", coreClock: "2310 MHz", boostClock: "2535 MHz", memoryBus: "128-bit", tdp: "165W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "16GB variant for more VRAM headroom in newer titles.",
  },
  {
    name: "AMD Radeon RX 7700 XT",
    category: "gpu",
    price: 399.99,
    rating: 4.6,
    reviewCount: 6800,
    imageUrl: "https://m.media-amazon.com/images/I/51eHGCy8C-L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CM8FQYL7",
    specs: JSON.stringify({ vram: "12GB GDDR6", coreClock: "1700 MHz", boostClock: "2544 MHz", memoryBus: "192-bit", tdp: "245W", ports: "HDMI 2.1, 2x DP 2.1" }),
    featured: false,
    description: "Competitive 1440p AMD card with 12GB VRAM.",
  },
  {
    name: "MSI GeForce RTX 4090 Suprim X",
    category: "gpu",
    price: 1799.99,
    rating: 4.9,
    reviewCount: 3100,
    imageUrl: "https://m.media-amazon.com/images/I/61NVfoVx0QL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BL3XDXLF",
    specs: JSON.stringify({ vram: "24GB GDDR6X", coreClock: "2235 MHz", boostClock: "2640 MHz", memoryBus: "384-bit", tdp: "450W", ports: "HDMI 2.1, 3x DP 1.4a" }),
    featured: false,
    description: "Factory overclocked RTX 4090 with premium Suprim cooling.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // RAM — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Corsair Vengeance LPX 16GB DDR4-3200",
    category: "ram",
    price: 39.99,
    rating: 4.7,
    reviewCount: 92000,
    imageUrl: "https://m.media-amazon.com/images/I/51YFisXhxNL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0143UM4TC",
    specs: JSON.stringify({ capacity: "16GB (2×8GB)", speed: "3200 MHz", type: "DDR4", latency: "CL16", voltage: "1.35V", formFactor: "DIMM" }),
    featured: true,
    description: "Best-selling DDR4 kit — reliable and compatible with everything.",
  },
  {
    name: "G.Skill Trident Z5 RGB 32GB DDR5-6000",
    category: "ram",
    price: 99.99,
    rating: 4.8,
    reviewCount: 14800,
    imageUrl: "https://m.media-amazon.com/images/I/61SvPJWyz+L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B09QSJ5V8F",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "6000 MHz", type: "DDR5", latency: "CL30", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "Premium RGB DDR5 with tight CL30 timings — Ryzen 7000 sweet spot.",
  },
  {
    name: "Kingston Fury Beast 32GB DDR5-5600",
    category: "ram",
    price: 74.99,
    rating: 4.7,
    reviewCount: 11200,
    imageUrl: "https://m.media-amazon.com/images/I/41Ig6vmZVkL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B09WXDZL9C",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "5600 MHz", type: "DDR5", latency: "CL40", voltage: "1.25V", formFactor: "DIMM" }),
    featured: false,
    description: "Great DDR5 value with Intel XMP 3.0 and AMD EXPO support.",
  },
  {
    name: "Corsair Dominator Platinum RGB 32GB DDR5-6200",
    category: "ram",
    price: 149.99,
    rating: 4.9,
    reviewCount: 5600,
    imageUrl: "https://m.media-amazon.com/images/I/51bMLJ1Y3xL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BF56MRYQ",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "6200 MHz", type: "DDR5", latency: "CL30", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "Premium DDR5 with iCUE-controlled Capellix LED bar.",
  },
  {
    name: "Corsair Vengeance 32GB DDR5-5600",
    category: "ram",
    price: 79.99,
    rating: 4.6,
    reviewCount: 12000,
    imageUrl: "https://m.media-amazon.com/images/I/51YFisXhxNL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0C3XQFRQG",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "5600 MHz", type: "DDR5", latency: "CL36", voltage: "1.25V", formFactor: "DIMM" }),
    featured: false,
    description: "High-performance DDR5 optimized for Intel and AMD platforms.",
  },
  {
    name: "G.Skill Ripjaws V 32GB DDR4-3600",
    category: "ram",
    price: 64.99,
    rating: 4.8,
    reviewCount: 52000,
    imageUrl: "https://m.media-amazon.com/images/I/517hKpZK7oL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B07Z45XB3G",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "3600 MHz", type: "DDR4", latency: "CL18", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "Workhorse DDR4 kit for Ryzen 5000 builds.",
  },
  {
    name: "TeamGroup T-Force Vulcan Z 16GB DDR4-3200",
    category: "ram",
    price: 29.99,
    rating: 4.5,
    reviewCount: 22000,
    imageUrl: "https://m.media-amazon.com/images/I/41N4x7D4P4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B07T637L7T",
    specs: JSON.stringify({ capacity: "16GB (2×8GB)", speed: "3200 MHz", type: "DDR4", latency: "CL16", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "The cheapest decent DDR4 kit you can buy.",
  },
  {
    name: "Crucial Ballistix 16GB DDR4-3600",
    category: "ram",
    price: 49.99,
    rating: 4.7,
    reviewCount: 36000,
    imageUrl: "https://m.media-amazon.com/images/I/41V4HG7mp6L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B083TRRT16",
    specs: JSON.stringify({ capacity: "16GB (2×8GB)", speed: "3600 MHz", type: "DDR4", latency: "CL16", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "Excellent overclocking potential with Micron Rev.E dies.",
  },
  {
    name: "Kingston Fury Renegade 32GB DDR5-6400",
    category: "ram",
    price: 129.99,
    rating: 4.7,
    reviewCount: 4200,
    imageUrl: "https://m.media-amazon.com/images/I/41Ig6vmZVkL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BQ9JWP3Y",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "6400 MHz", type: "DDR5", latency: "CL32", voltage: "1.4V", formFactor: "DIMM" }),
    featured: false,
    description: "High-speed DDR5 for enthusiast builds.",
  },
  {
    name: "Patriot Viper Steel 16GB DDR4-4400",
    category: "ram",
    price: 69.99,
    rating: 4.4,
    reviewCount: 6100,
    imageUrl: "https://m.media-amazon.com/images/I/51DfMSNR4FL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B07KXNGMRL",
    specs: JSON.stringify({ capacity: "16GB (2×8GB)", speed: "4400 MHz", type: "DDR4", latency: "CL19", voltage: "1.45V", formFactor: "DIMM" }),
    featured: false,
    description: "High-frequency DDR4 for maximum Intel performance.",
  },
  {
    name: "G.Skill Trident Z5 Neo RGB 32GB DDR5-6000",
    category: "ram",
    price: 109.99,
    rating: 4.8,
    reviewCount: 8900,
    imageUrl: "https://m.media-amazon.com/images/I/61SvPJWyz+L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BT6ML4TK",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "6000 MHz", type: "DDR5", latency: "CL30", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "AMD EXPO optimized — designed specifically for Ryzen 7000.",
  },
  {
    name: "Corsair Vengeance RGB Pro 32GB DDR4-3600",
    category: "ram",
    price: 79.99,
    rating: 4.8,
    reviewCount: 28000,
    imageUrl: "https://m.media-amazon.com/images/I/51YFisXhxNL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B07D5RN3S4",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "3600 MHz", type: "DDR4", latency: "CL18", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "Beautiful RGB DDR4 with 10 individually addressable LEDs per stick.",
  },
  {
    name: "TeamGroup T-Force Delta RGB 32GB DDR5-5600",
    category: "ram",
    price: 84.99,
    rating: 4.6,
    reviewCount: 7200,
    imageUrl: "https://m.media-amazon.com/images/I/41N4x7D4P4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHZ5FG7P",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "5600 MHz", type: "DDR5", latency: "CL36", voltage: "1.25V", formFactor: "DIMM" }),
    featured: false,
    description: "Budget DDR5 with solid RGB and good XMP/EXPO compatibility.",
  },
  {
    name: "Crucial DDR5-4800 16GB",
    category: "ram",
    price: 39.99,
    rating: 4.5,
    reviewCount: 15000,
    imageUrl: "https://m.media-amazon.com/images/I/41V4HG7mp6L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B09MDBQ11T",
    specs: JSON.stringify({ capacity: "16GB (1×16GB)", speed: "4800 MHz", type: "DDR5", latency: "CL40", voltage: "1.1V", formFactor: "DIMM" }),
    featured: false,
    description: "Entry-level DDR5 — cheapest way to get on the DDR5 platform.",
  },
  {
    name: "Kingston Fury Beast RGB 32GB DDR5-6000",
    category: "ram",
    price: 94.99,
    rating: 4.7,
    reviewCount: 6800,
    imageUrl: "https://m.media-amazon.com/images/I/41Ig6vmZVkL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CK18B4NR",
    specs: JSON.stringify({ capacity: "32GB (2×16GB)", speed: "6000 MHz", type: "DDR5", latency: "CL30", voltage: "1.35V", formFactor: "DIMM" }),
    featured: false,
    description: "RGB-equipped DDR5 with competitive CL30 timings.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STORAGE — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Samsung 990 Pro 2TB NVMe SSD",
    category: "storage",
    price: 159.99,
    rating: 4.8,
    reviewCount: 22000,
    imageUrl: "https://m.media-amazon.com/images/I/31jGVzBJSIL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHJJ9Y77",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7450 MB/s", writeSpeed: "6900 MB/s", formFactor: "M.2 2280" }),
    featured: true,
    description: "Samsung's fastest PCIe 4.0 SSD with class-leading endurance.",
  },
  {
    name: "WD Black SN850X 1TB",
    category: "storage",
    price: 69.99,
    rating: 4.8,
    reviewCount: 26000,
    imageUrl: "https://m.media-amazon.com/images/I/31RDcBtad4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0B7CKVCCV",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7300 MB/s", writeSpeed: "6300 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "WD's top-tier gaming SSD with Game Mode 2.0.",
  },
  {
    name: "Crucial P3 Plus 1TB",
    category: "storage",
    price: 49.99,
    rating: 4.6,
    reviewCount: 17000,
    imageUrl: "https://m.media-amazon.com/images/I/31w-3ypXr4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0B25LZGGW",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "5000 MB/s", writeSpeed: "4200 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Budget NVMe SSD with decent speeds for the price.",
  },
  {
    name: "Samsung 870 EVO 1TB SATA SSD",
    category: "storage",
    price: 64.99,
    rating: 4.8,
    reviewCount: 74000,
    imageUrl: "https://m.media-amazon.com/images/I/41xFAlyXv-L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B08QBJ2YMG",
    specs: JSON.stringify({ capacity: "1TB", type: "SATA SSD", interface: "SATA III", readSpeed: "560 MB/s", writeSpeed: "530 MB/s", formFactor: "2.5 inch" }),
    featured: false,
    description: "Best SATA SSD on the market — ultra-reliable.",
  },
  {
    name: "Seagate Barracuda 2TB HDD",
    category: "storage",
    price: 44.99,
    rating: 4.6,
    reviewCount: 96000,
    imageUrl: "https://m.media-amazon.com/images/I/51GKCUaW5RL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B07H2RR55Q",
    specs: JSON.stringify({ capacity: "2TB", type: "HDD", interface: "SATA III", rpm: "7200 RPM", cache: "256MB", formFactor: "3.5 inch" }),
    featured: false,
    description: "Cheap mass storage for games and media.",
  },
  {
    name: "SK Hynix Platinum P41 2TB",
    category: "storage",
    price: 139.99,
    rating: 4.8,
    reviewCount: 7800,
    imageUrl: "https://m.media-amazon.com/images/I/31tEAuEPwNL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0B6DT57HV",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7000 MB/s", writeSpeed: "6500 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Excellent alternative to Samsung 990 Pro with great endurance.",
  },
  {
    name: "Kingston NV2 500GB",
    category: "storage",
    price: 24.99,
    rating: 4.5,
    reviewCount: 13000,
    imageUrl: "https://m.media-amazon.com/images/I/31C+0ILVhgL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BBWH81F2",
    specs: JSON.stringify({ capacity: "500GB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "3500 MB/s", writeSpeed: "2100 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Ultra-budget boot drive.",
  },
  {
    name: "Corsair MP600 PRO LPX 2TB",
    category: "storage",
    price: 174.99,
    rating: 4.7,
    reviewCount: 5100,
    imageUrl: "https://m.media-amazon.com/images/I/41Xp5Z5jk8L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0B27RCWPF",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7100 MB/s", writeSpeed: "6800 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "PS5-compatible NVMe with low-profile heatsink included.",
  },
  {
    name: "WD Blue SA510 1TB SATA SSD",
    category: "storage",
    price: 54.99,
    rating: 4.5,
    reviewCount: 11200,
    imageUrl: "https://m.media-amazon.com/images/I/31RDcBtad4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B09HKGGPLR",
    specs: JSON.stringify({ capacity: "1TB", type: "SATA SSD", interface: "SATA III", readSpeed: "560 MB/s", writeSpeed: "520 MB/s", formFactor: "2.5 inch" }),
    featured: false,
    description: "Affordable WD SATA SSD for laptops and desktops.",
  },
  {
    name: "Sabrent Rocket 4 Plus-G 4TB",
    category: "storage",
    price: 329.99,
    rating: 4.7,
    reviewCount: 2800,
    imageUrl: "https://m.media-amazon.com/images/I/41G2e4E3iRL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BYZ1Y45R",
    specs: JSON.stringify({ capacity: "4TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7100 MB/s", writeSpeed: "6600 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Massive 4TB NVMe for game libraries and video editing.",
  },
  {
    name: "Samsung 980 Pro 1TB",
    category: "storage",
    price: 79.99,
    rating: 4.8,
    reviewCount: 48000,
    imageUrl: "https://m.media-amazon.com/images/I/31jGVzBJSIL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B08GLX7TNT",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7000 MB/s", writeSpeed: "5000 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Previous-gen Samsung flagship — still very fast.",
  },
  {
    name: "WD Black SN850X 2TB",
    category: "storage",
    price: 139.99,
    rating: 4.8,
    reviewCount: 15000,
    imageUrl: "https://m.media-amazon.com/images/I/31RDcBtad4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0B7CPSN2K",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "7300 MB/s", writeSpeed: "6600 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "2TB variant of WD's top-tier gaming SSD.",
  },
  {
    name: "Crucial T700 2TB PCIe 5.0",
    category: "storage",
    price: 219.99,
    rating: 4.6,
    reviewCount: 3200,
    imageUrl: "https://m.media-amazon.com/images/I/31w-3ypXr4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0C3GGHKRK",
    specs: JSON.stringify({ capacity: "2TB", type: "NVMe M.2", interface: "PCIe 5.0 x4", readSpeed: "12400 MB/s", writeSpeed: "11800 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "First-gen PCIe 5.0 SSD with blazing sequential speeds.",
  },
  {
    name: "Samsung 990 EVO 1TB",
    category: "storage",
    price: 89.99,
    rating: 4.6,
    reviewCount: 5600,
    imageUrl: "https://m.media-amazon.com/images/I/31jGVzBJSIL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0CXKVGH9D",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 5.0 x2 / PCIe 4.0 x4", readSpeed: "5000 MB/s", writeSpeed: "4200 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Samsung's hybrid PCIe 5.0/4.0 SSD for ultrabooks and desktops.",
  },
  {
    name: "Crucial P5 Plus 1TB",
    category: "storage",
    price: 59.99,
    rating: 4.7,
    reviewCount: 18000,
    imageUrl: "https://m.media-amazon.com/images/I/31w-3ypXr4L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B098WL46RS",
    specs: JSON.stringify({ capacity: "1TB", type: "NVMe M.2", interface: "PCIe 4.0 x4", readSpeed: "6600 MB/s", writeSpeed: "5000 MB/s", formFactor: "M.2 2280" }),
    featured: false,
    description: "Mid-range NVMe with excellent sustained write performance.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOTHERBOARD — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "MSI MAG B650 Tomahawk WiFi",
    category: "motherboard",
    price: 189.99,
    rating: 4.7,
    reviewCount: 6400,
    imageUrl: "https://m.media-amazon.com/images/I/61+x9o6Q-NL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHCKJRTM",
    specs: JSON.stringify({ socket: "AM5", chipset: "B650", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6E" }),
    featured: true,
  },
  {
    name: "ASUS ROG Strix B760-A Gaming WiFi D4",
    category: "motherboard",
    price: 169.99,
    rating: 4.6,
    reviewCount: 4200,
    imageUrl: "https://m.media-amazon.com/images/I/81Y47t6CN3L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BG6JNXJY",
    specs: JSON.stringify({ socket: "LGA 1700", chipset: "B760", formFactor: "ATX", memorySlots: "4 × DDR4", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6" }),
    featured: false,
  },
  {
    name: "Gigabyte B550 AORUS Elite V2",
    category: "motherboard",
    price: 109.99,
    rating: 4.5,
    reviewCount: 14000,
    imageUrl: "https://m.media-amazon.com/images/I/71+Nz7a55wL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B08KWMXGPZ",
    specs: JSON.stringify({ socket: "AM4", chipset: "B550", formFactor: "ATX", memorySlots: "4 × DDR4", maxMemory: "128GB", m2Slots: "2", wifi: "No" }),
    featured: false,
  },
  {
    name: "MSI PRO Z790-P WiFi DDR5",
    category: "motherboard",
    price: 209.99,
    rating: 4.7,
    reviewCount: 5200,
    imageUrl: "https://m.media-amazon.com/images/I/61+x9o6Q-NL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BG6JC1P5",
    specs: JSON.stringify({ socket: "LGA 1700", chipset: "Z790", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "4", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "ASUS ROG Crosshair X670E Hero",
    category: "motherboard",
    price: 459.99,
    rating: 4.8,
    reviewCount: 2800,
    imageUrl: "https://m.media-amazon.com/images/I/81Y47t6CN3L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BDTMT5K1",
    specs: JSON.stringify({ socket: "AM5", chipset: "X670E", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "5", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "ASRock B660M Pro RS DDR4",
    category: "motherboard",
    price: 84.99,
    rating: 4.3,
    reviewCount: 7800,
    imageUrl: "https://m.media-amazon.com/images/I/61qZ72u5DYL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B09QYVMT2D",
    specs: JSON.stringify({ socket: "LGA 1700", chipset: "B660", formFactor: "Micro-ATX", memorySlots: "2 × DDR4", maxMemory: "64GB", m2Slots: "1", wifi: "No" }),
    featured: false,
  },
  {
    name: "Gigabyte X670E AORUS Master",
    category: "motherboard",
    price: 369.99,
    rating: 4.7,
    reviewCount: 2200,
    imageUrl: "https://m.media-amazon.com/images/I/71+Nz7a55wL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BDTMSZW3",
    specs: JSON.stringify({ socket: "AM5", chipset: "X670E", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "4", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "MSI MAG B550 Tomahawk",
    category: "motherboard",
    price: 129.99,
    rating: 4.7,
    reviewCount: 24000,
    imageUrl: "https://m.media-amazon.com/images/I/61+x9o6Q-NL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B089CWDHFZ",
    specs: JSON.stringify({ socket: "AM4", chipset: "B550", formFactor: "ATX", memorySlots: "4 × DDR4", maxMemory: "128GB", m2Slots: "2", wifi: "No" }),
    featured: false,
  },
  {
    name: "ASUS Prime B760M-A WiFi D4",
    category: "motherboard",
    price: 119.99,
    rating: 4.5,
    reviewCount: 8800,
    imageUrl: "https://m.media-amazon.com/images/I/81Y47t6CN3L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BG6MGL2G",
    specs: JSON.stringify({ socket: "LGA 1700", chipset: "B760", formFactor: "Micro-ATX", memorySlots: "4 × DDR4", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6" }),
    featured: false,
  },
  {
    name: "Gigabyte Z790 AORUS Elite AX DDR5",
    category: "motherboard",
    price: 239.99,
    rating: 4.6,
    reviewCount: 3600,
    imageUrl: "https://m.media-amazon.com/images/I/71+Nz7a55wL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHC9SFKG",
    specs: JSON.stringify({ socket: "LGA 1700", chipset: "Z790", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "4", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "MSI MAG B650M Mortar WiFi",
    category: "motherboard",
    price: 179.99,
    rating: 4.7,
    reviewCount: 4100,
    imageUrl: "https://m.media-amazon.com/images/I/61+x9o6Q-NL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHCGDPXF",
    specs: JSON.stringify({ socket: "AM5", chipset: "B650", formFactor: "Micro-ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "ASUS TUF Gaming B650-Plus WiFi",
    category: "motherboard",
    price: 199.99,
    rating: 4.6,
    reviewCount: 5500,
    imageUrl: "https://m.media-amazon.com/images/I/81Y47t6CN3L._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHCHR7ZQ",
    specs: JSON.stringify({ socket: "AM5", chipset: "B650", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6" }),
    featured: false,
  },
  {
    name: "ASRock B650E PG Riptide WiFi",
    category: "motherboard",
    price: 159.99,
    rating: 4.4,
    reviewCount: 3200,
    imageUrl: "https://m.media-amazon.com/images/I/61qZ72u5DYL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHJDQXZ6",
    specs: JSON.stringify({ socket: "AM5", chipset: "B650E", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "3", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "Gigabyte B650 AORUS Elite AX",
    category: "motherboard",
    price: 179.99,
    rating: 4.6,
    reviewCount: 4800,
    imageUrl: "https://m.media-amazon.com/images/I/71+Nz7a55wL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BHCJ7SQJ",
    specs: JSON.stringify({ socket: "AM5", chipset: "B650", formFactor: "ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6E" }),
    featured: false,
  },
  {
    name: "MSI PRO B760M-A WiFi DDR5",
    category: "motherboard",
    price: 139.99,
    rating: 4.5,
    reviewCount: 6200,
    imageUrl: "https://m.media-amazon.com/images/I/61+x9o6Q-NL._AC_SL1500_.jpg",
    productUrl: "https://www.amazon.com/dp/B0BG6KJ3VH",
    specs: JSON.stringify({ socket: "LGA 1700", chipset: "B760", formFactor: "Micro-ATX", memorySlots: "4 × DDR5", maxMemory: "128GB", m2Slots: "2", wifi: "WiFi 6E" }),
    featured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PC CASE — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "NZXT H5 Flow", category: "case", price: 89.99, rating: 4.7, reviewCount: 10200, imageUrl: "https://m.media-amazon.com/images/I/71U3fQGcm9L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0B6CG9BLH", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '18.1×8.6×17.1"', fanSupport: "6×120mm", maxGpuLength: "365mm", frontIO: "USB-C, 2× USB-A" }), featured: true },
  { name: "Corsair 4000D Airflow", category: "case", price: 99.99, rating: 4.7, reviewCount: 36000, imageUrl: "https://m.media-amazon.com/images/I/81E5WhIiPBL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08C76W2WM", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '18.7×9.1×17.8"', fanSupport: "6×120mm", maxGpuLength: "360mm", frontIO: "USB-C, USB-A" }), featured: false },
  { name: "Fractal Design North", category: "case", price: 129.99, rating: 4.8, reviewCount: 6200, imageUrl: "https://m.media-amazon.com/images/I/81Y47t6CN3L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BYCQYHLW", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '18.3×8.5×17.6"', fanSupport: "6×120mm / 3×140mm", maxGpuLength: "355mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Lian Li Lancool II Mesh", category: "case", price: 99.99, rating: 4.8, reviewCount: 16000, imageUrl: "https://m.media-amazon.com/images/I/71T5ms83GaL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08DX68X8S", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '19.0×9.0×18.5"', fanSupport: "7×120mm", maxGpuLength: "384mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Phanteks Eclipse G360A", category: "case", price: 84.99, rating: 4.6, reviewCount: 9000, imageUrl: "https://m.media-amazon.com/images/I/71TkCPpgqZL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09GFR7TL5", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '18.5×8.3×17.1"', fanSupport: "6×120mm", maxGpuLength: "380mm", frontIO: "USB-C, USB-A" }), featured: false },
  { name: "be quiet! Pure Base 500DX", category: "case", price: 104.99, rating: 4.7, reviewCount: 10800, imageUrl: "https://m.media-amazon.com/images/I/81IiTtVwXBL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B087TNVS2Z", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '18.9×9.1×17.5"', fanSupport: "5×120/140mm", maxGpuLength: "369mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Cooler Master MasterBox Q300L", category: "case", price: 44.99, rating: 4.4, reviewCount: 21000, imageUrl: "https://m.media-amazon.com/images/I/71akSrUKqdL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0785GRMPG", specs: JSON.stringify({ formFactor: "Micro-ATX", dimensions: '15.6×9.1×14.8"', fanSupport: "4×120mm", maxGpuLength: "360mm", frontIO: "2× USB-A" }), featured: false },
  { name: "Lian Li O11 Dynamic EVO", category: "case", price: 159.99, rating: 4.8, reviewCount: 7800, imageUrl: "https://m.media-amazon.com/images/I/71T5ms83GaL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09TMHKBRP", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '20.2×11.2×18.6"', fanSupport: "9×120mm", maxGpuLength: "422mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Corsair 5000D Airflow", category: "case", price: 154.99, rating: 4.7, reviewCount: 10200, imageUrl: "https://m.media-amazon.com/images/I/81E5WhIiPBL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08C7BGV3J", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '20.5×9.1×20.5"', fanSupport: "10×120mm", maxGpuLength: "420mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Thermaltake S100 TG", category: "case", price: 59.99, rating: 4.3, reviewCount: 5200, imageUrl: "https://m.media-amazon.com/images/I/71jJ3aTF54L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08GQD7Y5J", specs: JSON.stringify({ formFactor: "Micro-ATX", dimensions: '16.7×8.0×15.0"', fanSupport: "4×120mm", maxGpuLength: "330mm", frontIO: "2× USB-A" }), featured: false },
  { name: "NZXT H7 Flow", category: "case", price: 129.99, rating: 4.7, reviewCount: 4500, imageUrl: "https://m.media-amazon.com/images/I/71U3fQGcm9L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BLQFK1BS", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '19.5×9.1×18.3"', fanSupport: "7×120mm", maxGpuLength: "400mm", frontIO: "USB-C, USB-A" }), featured: false },
  { name: "Fractal Design Torrent", category: "case", price: 179.99, rating: 4.8, reviewCount: 3200, imageUrl: "https://m.media-amazon.com/images/I/81Y47t6CN3L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09K3WQBB6", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '21.8×9.4×20.1"', fanSupport: "5×140mm + 2×180mm", maxGpuLength: "461mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Cooler Master HAF 700 EVO", category: "case", price: 299.99, rating: 4.7, reviewCount: 1800, imageUrl: "https://m.media-amazon.com/images/I/71akSrUKqdL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0B3RXJWL5", specs: JSON.stringify({ formFactor: "Full-Tower", dimensions: '24.8×10.8×22.4"', fanSupport: "12×120mm", maxGpuLength: "490mm", frontIO: "USB-C, 4× USB-A" }), featured: false },
  { name: "Lian Li Lancool III", category: "case", price: 139.99, rating: 4.7, reviewCount: 5100, imageUrl: "https://m.media-amazon.com/images/I/71T5ms83GaL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BG72G1S5", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '20.1×9.3×19.6"', fanSupport: "9×120mm", maxGpuLength: "420mm", frontIO: "USB-C, 2× USB-A" }), featured: false },
  { name: "Corsair iCUE 5000T RGB", category: "case", price: 349.99, rating: 4.6, reviewCount: 2400, imageUrl: "https://m.media-amazon.com/images/I/81E5WhIiPBL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09VXXQFC1", specs: JSON.stringify({ formFactor: "Mid-Tower ATX", dimensions: '20.5×10.5×20.5"', fanSupport: "10×120mm", maxGpuLength: "400mm", frontIO: "USB-C, 4× USB-A" }), featured: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // COOLING — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "Noctua NH-D15", category: "cooling", price: 109.99, rating: 4.9, reviewCount: 28000, imageUrl: "https://m.media-amazon.com/images/I/91Nk20lqX3L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B00L7UZMAK", specs: JSON.stringify({ type: "Air Cooler", fanSize: "2×140mm", height: "165mm", tdpRating: "250W+", noise: "24.6 dBA", socket: "Intel & AMD" }), featured: true },
  { name: "Corsair iCUE H150i Elite Capellix", category: "cooling", price: 159.99, rating: 4.7, reviewCount: 13000, imageUrl: "https://m.media-amazon.com/images/I/71E-vTRNyGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08G1LPKGC", specs: JSON.stringify({ type: "AIO Liquid 360mm", fanSize: "3×120mm", radiator: "360mm", tdpRating: "300W+", noise: "10-36 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "be quiet! Dark Rock Pro 4", category: "cooling", price: 84.99, rating: 4.8, reviewCount: 15000, imageUrl: "https://m.media-amazon.com/images/I/81rwV-DYRbL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B07BY6F1TI", specs: JSON.stringify({ type: "Air Cooler", fanSize: "1×120mm + 1×135mm", height: "163mm", tdpRating: "250W", noise: "24.3 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "ARCTIC Liquid Freezer II 280", category: "cooling", price: 94.99, rating: 4.8, reviewCount: 10200, imageUrl: "https://m.media-amazon.com/images/I/71LiWJtLN0L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B07WP6M7P7", specs: JSON.stringify({ type: "AIO Liquid 280mm", fanSize: "2×140mm", radiator: "280mm", tdpRating: "300W+", noise: "22.5 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "Thermalright Peerless Assassin 120 SE", category: "cooling", price: 34.99, rating: 4.7, reviewCount: 18000, imageUrl: "https://m.media-amazon.com/images/I/71GHfOmlxOL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09LGY38L4", specs: JSON.stringify({ type: "Air Cooler", fanSize: "2×120mm", height: "155mm", tdpRating: "230W", noise: "25.6 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "NZXT Kraken X63", category: "cooling", price: 109.99, rating: 4.6, reviewCount: 8800, imageUrl: "https://m.media-amazon.com/images/I/71e8hbJAc8L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B082DYR131", specs: JSON.stringify({ type: "AIO Liquid 280mm", fanSize: "2×140mm", radiator: "280mm", tdpRating: "280W", noise: "21-38 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "Cooler Master Hyper 212 EVO V2", category: "cooling", price: 32.99, rating: 4.5, reviewCount: 46000, imageUrl: "https://m.media-amazon.com/images/I/71GuLT+7sjL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08LR3SBT8", specs: JSON.stringify({ type: "Air Cooler", fanSize: "1×120mm", height: "159mm", tdpRating: "150W", noise: "27 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "DeepCool AK620", category: "cooling", price: 59.99, rating: 4.8, reviewCount: 10800, imageUrl: "https://m.media-amazon.com/images/I/71AvECYtjKL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09DJFKHCJ", specs: JSON.stringify({ type: "Air Cooler", fanSize: "2×120mm", height: "160mm", tdpRating: "260W", noise: "28 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "Lian Li Galahad II Trinity 360", category: "cooling", price: 139.99, rating: 4.7, reviewCount: 3800, imageUrl: "https://m.media-amazon.com/images/I/71QX9WC6MRL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0CN18WQXY", specs: JSON.stringify({ type: "AIO Liquid 360mm", fanSize: "3×120mm", radiator: "360mm", tdpRating: "300W+", noise: "29 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "ID-COOLING SE-214-XT", category: "cooling", price: 17.99, rating: 4.5, reviewCount: 19000, imageUrl: "https://m.media-amazon.com/images/I/71E9CDQK1kL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09BQNQKPS", specs: JSON.stringify({ type: "Air Cooler", fanSize: "1×120mm", height: "150mm", tdpRating: "180W", noise: "26.2 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "Noctua NH-U12S", category: "cooling", price: 69.99, rating: 4.8, reviewCount: 22000, imageUrl: "https://m.media-amazon.com/images/I/91Nk20lqX3L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B00C9FLSLY", specs: JSON.stringify({ type: "Air Cooler", fanSize: "1×120mm", height: "158mm", tdpRating: "200W", noise: "22.4 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "EK-AIO 360 D-RGB", category: "cooling", price: 149.99, rating: 4.7, reviewCount: 4200, imageUrl: "https://m.media-amazon.com/images/I/71LiWJtLN0L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09V1KGTPH", specs: JSON.stringify({ type: "AIO Liquid 360mm", fanSize: "3×120mm", radiator: "360mm", tdpRating: "300W+", noise: "28 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "ARCTIC Liquid Freezer II 360", category: "cooling", price: 109.99, rating: 4.8, reviewCount: 8500, imageUrl: "https://m.media-amazon.com/images/I/71LiWJtLN0L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B07WNRM8V6", specs: JSON.stringify({ type: "AIO Liquid 360mm", fanSize: "3×120mm", radiator: "360mm", tdpRating: "300W+", noise: "22.5 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "Thermalright Frost Commander 140", category: "cooling", price: 44.99, rating: 4.7, reviewCount: 6200, imageUrl: "https://m.media-amazon.com/images/I/71GHfOmlxOL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BK8JFRNG", specs: JSON.stringify({ type: "Air Cooler", fanSize: "2×120mm + 1×140mm", height: "165mm", tdpRating: "260W", noise: "25 dBA", socket: "Intel & AMD" }), featured: false },
  { name: "Corsair iCUE H100i Elite LCD XT", category: "cooling", price: 179.99, rating: 4.7, reviewCount: 3100, imageUrl: "https://m.media-amazon.com/images/I/71E-vTRNyGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0CFWRMMPF", specs: JSON.stringify({ type: "AIO Liquid 240mm", fanSize: "2×120mm", radiator: "240mm", tdpRating: "250W", noise: "10-33 dBA", socket: "Intel & AMD" }), featured: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // PSU — 15 products
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "Corsair RM850x (2023)", category: "psu", price: 129.99, rating: 4.8, reviewCount: 18000, imageUrl: "https://m.media-amazon.com/images/I/71U92FVqSGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BYM5YPC3", specs: JSON.stringify({ wattage: "850W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP", warranty: "10 years" }), featured: true },
  { name: "EVGA SuperNOVA 750 G7", category: "psu", price: 99.99, rating: 4.7, reviewCount: 10200, imageUrl: "https://m.media-amazon.com/images/I/71zHF7e6mNL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09J2JBQJZ", specs: JSON.stringify({ wattage: "750W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "130mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }), featured: false },
  { name: "Seasonic Focus GX-650", category: "psu", price: 84.99, rating: 4.7, reviewCount: 14000, imageUrl: "https://m.media-amazon.com/images/I/71KwKIgUKEL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B077J9QTDR", specs: JSON.stringify({ wattage: "650W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "120mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "10 years" }), featured: false },
  { name: "be quiet! Straight Power 12 1000W", category: "psu", price: 179.99, rating: 4.8, reviewCount: 4000, imageUrl: "https://m.media-amazon.com/images/I/81IiTtVwXBL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BMDX5C9N", specs: JSON.stringify({ wattage: "1000W", efficiency: "80+ Platinum", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "10 years" }), featured: false },
  { name: "Thermaltake Toughpower GF3 850W", category: "psu", price: 114.99, rating: 4.6, reviewCount: 6400, imageUrl: "https://m.media-amazon.com/images/I/71fQ8FfkCEL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BGPCHTQN", specs: JSON.stringify({ wattage: "850W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "120mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }), featured: false },
  { name: "Corsair CX550F RGB", category: "psu", price: 64.99, rating: 4.4, reviewCount: 11200, imageUrl: "https://m.media-amazon.com/images/I/71U92FVqSGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B08FVKRC96", specs: JSON.stringify({ wattage: "550W", efficiency: "80+ Bronze", modular: "Fully Modular", fanSize: "120mm RGB", protections: "OVP, UVP, SCP, OTP", warranty: "5 years" }), featured: false },
  { name: "NZXT C1200 Gold", category: "psu", price: 189.99, rating: 4.7, reviewCount: 2800, imageUrl: "https://m.media-amazon.com/images/I/71e8hbJAc8L._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0CK3MB12V", specs: JSON.stringify({ wattage: "1200W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "140mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }), featured: false },
  { name: "MSI MAG A650BN", category: "psu", price: 49.99, rating: 4.3, reviewCount: 7400, imageUrl: "https://m.media-amazon.com/images/I/61+x9o6Q-NL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BGPR87TG", specs: JSON.stringify({ wattage: "650W", efficiency: "80+ Bronze", modular: "Non-Modular", fanSize: "120mm", protections: "OVP, UVP, SCP, OTP", warranty: "5 years" }), featured: false },
  { name: "Corsair HX1500i", category: "psu", price: 339.99, rating: 4.9, reviewCount: 2200, imageUrl: "https://m.media-amazon.com/images/I/71U92FVqSGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BTFX94N3", specs: JSON.stringify({ wattage: "1500W", efficiency: "80+ Platinum", modular: "Fully Modular", fanSize: "140mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "10 years" }), featured: false },
  { name: "Cooler Master V750 SFX Gold", category: "psu", price: 119.99, rating: 4.6, reviewCount: 5200, imageUrl: "https://m.media-amazon.com/images/I/71GuLT+7sjL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09NS5YB3F", specs: JSON.stringify({ wattage: "750W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "92mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }), featured: false },
  { name: "Corsair RM1000e", category: "psu", price: 159.99, rating: 4.7, reviewCount: 6800, imageUrl: "https://m.media-amazon.com/images/I/71U92FVqSGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B0BF6K193K", specs: JSON.stringify({ wattage: "1000W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }), featured: false },
  { name: "Seasonic Prime TX-1000", category: "psu", price: 279.99, rating: 4.9, reviewCount: 1500, imageUrl: "https://m.media-amazon.com/images/I/71KwKIgUKEL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B07WVMDZMG", specs: JSON.stringify({ wattage: "1000W", efficiency: "80+ Titanium", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "12 years" }), featured: false },
  { name: "EVGA SuperNOVA 850 G6", category: "psu", price: 109.99, rating: 4.7, reviewCount: 8200, imageUrl: "https://m.media-amazon.com/images/I/71zHF7e6mNL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B09J2J2KHZ", specs: JSON.stringify({ wattage: "850W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "135mm", protections: "OVP, UVP, SCP, OTP, OCP", warranty: "10 years" }), featured: false },
  { name: "Corsair SF750 Platinum", category: "psu", price: 159.99, rating: 4.8, reviewCount: 12000, imageUrl: "https://m.media-amazon.com/images/I/71U92FVqSGL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B07M63H81H", specs: JSON.stringify({ wattage: "750W", efficiency: "80+ Platinum", modular: "Fully Modular", fanSize: "92mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "7 years" }), featured: false },
  { name: "Super Flower Leadex III 850W", category: "psu", price: 109.99, rating: 4.7, reviewCount: 4500, imageUrl: "https://m.media-amazon.com/images/I/71fQ8FfkCEL._AC_SL1500_.jpg", productUrl: "https://www.amazon.com/dp/B07THDQBHK", specs: JSON.stringify({ wattage: "850W", efficiency: "80+ Gold", modular: "Fully Modular", fanSize: "130mm", protections: "OVP, UVP, SCP, OTP, OCP, OPP", warranty: "7 years" }), featured: false },
];

// ─── Main seed function ─────────────────────────────────────────────────────

async function main() {
  console.log(`\n🔧 Seeding ${products.length} products...\n`);

  // Group by category for bestValue calculation
  const byCategory: Record<string, SeedProduct[]> = {};
  for (const p of products) {
    if (!byCategory[p.category]) byCategory[p.category] = [];
    byCategory[p.category].push(p);
  }

  let created = 0;
  let updated = 0;

  for (const [category, group] of Object.entries(byCategory)) {
    console.log(`  📁 ${category} — ${group.length} products`);

    for (const p of group) {
      const bestValue = calculateBestValue(p, group);
      const affiliateUrl = generateAffiliateLink(p.productUrl);

      const data = {
        category: p.category,
        price: p.price,
        rating: p.rating,
        reviewCount: p.reviewCount,
        imageUrl: p.imageUrl,
        productUrl: p.productUrl,
        affiliateUrl,
        specs: p.specs,
        description: p.description ?? null,
        bestValue,
        featured: p.featured,
        inStock: true,
      };

      const result = await prisma.product.upsert({
        where: { name: p.name },
        update: data,
        create: { name: p.name, ...data },
      });

      // Check if it was created or updated by comparing timestamps
      const isNew = result.lastUpdated.getTime() - Date.now() < 1000;
      if (isNew) created++;
      else updated++;
    }
  }

  const total = await prisma.product.count();
  console.log(`\n✅ Seed complete!`);
  console.log(`   ${products.length} processed | ${total} total in DB\n`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
